<?xml version="1.0" encoding="UTF-8"?>
<!--
  * version.xml
  *
  * Copyright (c) 2003-2008 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * OJS version information.
  *
  * $Id$
  -->
<!DOCTYPE version [
	<!ELEMENT version (application, type, release, tag, date, info, package, patch+)>
	<!ELEMENT application (#PCDATA)>
	<!ELEMENT type (#PCDATA)>
	<!ELEMENT release (#PCDATA)>
	<!ELEMENT tag (#PCDATA)>
	<!ELEMENT date (#PCDATA)>
]>
<version>
	<application>jquery</application>
	<type>plugins.generic</type>
	<release>1.0.0.0</release>
	<tag>developedBy-1_0_0-0</tag>
	<date>2008-12-06</date>
</version>