=== jardakotesovec/pkp-mono/ojs/dbscripts/xml/dtd/xmldata.dtd
<!--
  * xmldata.dtd
  *
  * DTD for database data files.
  * Describes data to be inserted into a database.
  *
  * $Id$
  -->

<!ELEMENT data (table*, sql*)>
<!ELEMENT table (field_default*, row*)>
	<!ATTLIST table
		name CDATA #REQUIRED>
<!ELEMENT field_default (#PCDATA)>
	<!ATTLIST field_default
		name CDATA #REQUIRED
		null (0|1) #REQUIRED>
<!ELEMENT row (field+)>
<!ELEMENT field (#PCDATA)>
	<!ATTLIST field
		name CDATA #REQUIRED
		null (0|1) #REQUIRED>
<!ELEMENT sql (query*)>
<!ELEMENT query (#PCDATA)>

=== jardakotesovec/pkp-mono/omp/dbscripts/xml/data/locale/it_IT/email_templates_data.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE data SYSTEM "../../../../../lib/pkp/dtd/xmlData.dtd">

<!--
  * email_templates_data.xml
  *
  * Copyright (c) 2003-2008 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * Email templates data XML file (Italian).
  * Thanks to AePIC Team CILEA.
  *
  * $Id$
  -->

<data>
	<table name="email_templates_default_data">
		<field_default name="locale">it_IT</field_default>

		<!--
		  *
		  * General
		  *
		  -->
		<row>
			<field name="email_key">PASSWORD_RESET_CONFIRM</field>
			<field name="subject">Password Resetta Conferma</field>
			<field name="body">Abbiamo ricevuto una richiesta di resettare la password per il sito web {$siteTitle}.

Se non hai fatto questa richiesta, si prega di ignorare questa email e la password non sar&#x00E0; modificata. Se desisderi resettare la password, clica sulla URL di sotto.

Resetta la mia password: {$url}

{$principalContactSignature}</field>
			<field name="description">Questa email viene mandata ad un utente registrato quando questi indica che ha dimenticato la sua password o non riesce a fare il log in. Questa fornisce una URL che possono seguire per resettare la loro password.</field>
		</row>
		<row>
			<field name="email_key">PASSWORD_RESET</field>
			<field name="subject">Password Reset</field>
			<field name="body">La tua password &#x00E8; stata resettata con successo per questo sito web {$siteTitle}. Si prega di ricordare questa username e password, dato che &#x00E8; necessaria per tutto il lavoro con il journal.

La tua username: {$username}
La tua nuova password: {$password}

{$principalContactSignature}</field>
			<field name="description">Questa email viene mandata ad un utente registrato quando ha resettato la password seguendo il processo descritto nella email PASSWORD_RESETTA_CONFERMA.</field>
		</row>
		<row>
			<field name="email_key">USER_REGISTER</field>
			<field name="subject">Registrazione nuovo utente</field>
			<field name="body">Grazie per esserti registrato come utente a  {$journalName}. Si prega di mantenere la username e password, che sono necessarie per tutto il lavoro con questo journal.

Username: {$username}
Password: {$password}

Grazie,
{$principalContactSignature}</field>
			<field name="description">Questa email viene mandata agli utenti appena registrati per dar loro il benvenuto nel sistema e fornirgli una nota della loro username e password.</field>
		</row>
		<row>
			<field name="email_key">USER_VALIDATE</field>
			<field name="subject">Convalida il tuo account</field>
			<field name="body">{$userFullName}

Hai creato un account in {$journalName}, ma prima che tu possa usarlo, devi caonvalidare la email del tuo account. Per farlo, segui semplicemente il link qui sotto:

{$activateUrl}

Grazie,
{$principalContactSignature}</field>
			<field name="description">Questa email viene spedita a un nuovo utente registrato come benvenuto nel sistema e gli fornisce una nota con il suo nome utente e password.</field>
		</row>
	</table>
</data>

=== jardakotesovec/pkp-mono/omp/dbscripts/xml/upgrade/3.2.0_preupdate_versioning.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE data SYSTEM "../../../lib/pkp/dtd/xmlData.dtd">

<!--
	* dbscripts/xml/upgrade/3.2.0_preupdate_versioning.xml
	*
	* Copyright (c) 2013-2019 Simon Fraser University
	* Copyright (c) 2003-2019 John Willinsky
	* Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
	*
	* Copy submission data to temporary tables so it can be updated
	* after the publication table modifications are made.
	*
	-->

<data>
	<sql>
		<query>CREATE TABLE temp_authors AS SELECT * FROM authors</query>
		<query>CREATE TABLE temp_submissions AS SELECT * FROM submissions</query>
		<query>CREATE TABLE temp_submission_categories AS SELECT * FROM submission_categories</query>
		<query>CREATE TABLE temp_publication_formats AS SELECT * FROM publication_formats</query>
		<query>CREATE TABLE temp_submission_chapters AS SELECT * FROM submission_chapters</query>
		<query>CREATE TABLE temp_published_submissions AS SELECT * FROM published_submissions</query>
	</sql>
</data>

=== jardakotesovec/pkp-mono/omp/dbscripts/xml/upgrade/3.2.0_preupdate_email_templates.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE data SYSTEM "../../../lib/pkp/dtd/xmlData.dtd">

<!--
	* dbscripts/xml/upgrade/3.2.0_preupdate_email_templates.xml
	*
	* Copyright (c) 2013-2019 Simon Fraser University
	* Copyright (c) 2003-2019 John Willinsky
	* Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
	*
	* Update the email templates tables to remove unused columns, add a new
	* email_id column and primary key, and update outdated role ids for the
	* default templates.
	*
	-->

<data>
	<sql>
		<query>
			ALTER TABLE email_templates_data
			ADD email_id BIGINT NOT NULL
		</query>
		<query>
			UPDATE email_templates_data as etd
			SET etd.email_id = (
				SELECT et.email_id
				FROM email_templates as et
				WHERE etd.email_key = et.email_key
					AND etd.assoc_type = et.assoc_type
					AND etd.assoc_id = et.assoc_id
			)
		</query>
		<query>
			CREATE TABLE email_templates_settings (
				email_id INT,
				locale VARCHAR(14) NOT NULL DEFAULT '',
				setting_name VARCHAR(255) NOT NULL,
				setting_value text NULL,
				PRIMARY KEY (email_id,locale,setting_name)
			)
		</query>
		<query>
			INSERT INTO email_templates_settings (email_id, locale, setting_value, setting_name)
			SELECT email_id, locale, subject, 'subject'
			FROM email_templates_data
		</query>
		<query>
			INSERT INTO email_templates_settings (email_id, locale, setting_value, setting_name)
			SELECT email_id, locale, body, 'body'
			FROM email_templates_data
		</query>
		<query>
			DROP TABLE email_templates_data
		</query>
		<query>
			ALTER TABLE email_templates
			ADD context_id BIGINT
		</query>
		<query>
			UPDATE email_templates SET context_id = assoc_id
			WHERE assoc_type=256 AND assoc_id IS NOT NULL
		</query>
		<query>
			ALTER TABLE email_templates
			DROP INDEX email_templates_assoc,
			DROP INDEX email_templates_email_key
		</query>
		<query>
			ALTER TABLE email_templates
			DROP COLUMN assoc_type,
			DROP COLUMN assoc_id
		</query>
		<!-- 16 = ROLE_ID_MANAGER, 17 = ROLE_ID_SUB_EDITOR, 256 and 512 = unused role ids -->
		<query>
			UPDATE email_templates_default
			SET from_role_id=16
			WHERE from_role_id=17 OR from_role_id=256 OR from_role_id=512
		</query>
		<!-- 16 = ROLE_ID_MANAGER, 17 = ROLE_ID_SUB_EDITOR, 256 and 512 = unused role ids -->
		<query>
			UPDATE email_templates_default
			SET to_role_id=16
			WHERE to_role_id=17 OR to_role_id=256 OR to_role_id=512
		</query>
		<!-- 4097 = ROLE_ID_ASSISTANT, 768 and 8192 = unused role ids -->
		<query>
			UPDATE email_templates_default
			SET from_role_id=4097
			WHERE from_role_id=768 OR from_role_id=8192
		</query>
		<!-- 4097 = ROLE_ID_ASSISTANT, 768 and 8192 = unused role ids -->
		<query>
			UPDATE email_templates_default
			SET to_role_id=4097
			WHERE to_role_id=768 OR to_role_id=8192
		</query>
	</sql>
</data>

=== jardakotesovec/pkp-mono/omp/dbscripts/xml/upgrade/1.1.0.0_update.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE data SYSTEM "../../../lib/pkp/dtd/xmlData.dtd">

<!--
  * 1.0.0.0_update.xml
  *
  * Copyright (c) 2003-2013 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * 1.0.0.0 database updates XML file.
  -->
<data>
	<!-- synchronize the ASSOC_TYPE_MONOGRAPH constant to ASSOC_TYPE_SUBMISSION defined in PKPApplication -->
	<sql>
		<query>UPDATE controlled_vocabs SET assoc_type = '1048585' WHERE assoc_type = '513'</query>
		<query>UPDATE notifications SET assoc_type = '1048585' WHERE assoc_type = '513'</query>
		<query>UPDATE notes SET assoc_type = '1048585' WHERE assoc_type = '513'</query>
		<query>UPDATE email_log SET assoc_type = '1048585' WHERE assoc_type = '513'</query>
		<query>UPDATE event_log SET assoc_type = '1048585' WHERE assoc_type = '513'</query>

		<!-- rename the symbolic controlled vocab fields to the generic pkp-lib field name -->
		<query>UPDATE controlled_vocabs SET symbolic = 'submissionAgency' WHERE symbolic = 'monographAgency'</query>
		<query>UPDATE controlled_vocabs SET symbolic = 'submissionDiscipline' WHERE symbolic = 'monographDiscipline'</query>
		<query>UPDATE controlled_vocabs SET symbolic = 'submissionKeyword' WHERE symbolic = 'monographKeyword'</query>
		<query>UPDATE controlled_vocabs SET symbolic = 'submissionLanguage' WHERE symbolic = 'monographLanguage'</query>
		<query>UPDATE controlled_vocabs SET symbolic = 'submissionSubject' WHERE symbolic = 'monographSubject'</query>

		<query>UPDATE controlled_vocab_entry_settings SET setting_name = 'submissionAgency' WHERE setting_name = 'monographAgency'</query>
		<query>UPDATE controlled_vocab_entry_settings SET setting_name = 'submissionDiscipline' WHERE setting_name = 'monographDiscipline'</query>
		<query>UPDATE controlled_vocab_entry_settings SET setting_name = 'submissionKeyword' WHERE setting_name = 'monographKeyword'</query>
		<query>UPDATE controlled_vocab_entry_settings SET setting_name = 'submissionLanguage' WHERE setting_name = 'monographLanguage'</query>
		<query>UPDATE controlled_vocab_entry_settings SET setting_name = 'submissionSubject' WHERE setting_name = 'monographSubject'</query>
		<!--  make ROLE_ID_READER value the same across all PKP applications -->
		<query>UPDATE user_groups SET role_id = '1048576' WHERE role_id = '131072'</query>
		<!-- make ROLE_ID_MANAGER value the same as the one used in OJS (and now everywhere) -->
		<query>UPDATE user_groups SET role_id = '16' WHERE role_id = '17'</query>

	</sql>
	<!-- Bug #8094: Rename settings for standardization -->
	<sql>
		<query>UPDATE press_settings SET setting_name = 'pageHeader' WHERE setting_name = 'pressPageHeader'</query>
		<query>UPDATE press_settings SET setting_name = 'pageFooter' WHERE setting_name = 'pressPageFooter'</query>
		<query>UPDATE press_settings SET setting_name = 'styleSheet' WHERE setting_name = 'pressStyleSheet'</query>
		<query>UPDATE press_settings SET setting_name = 'currency' WHERE setting_name = 'pressCurrency'</query>
	</sql>
	<!-- Bug #8163: Allow restriction of review files in assignments -->
	<sql>
		<!-- For existing assignments, all files are permitted. -->
		<query>INSERT IGNORE INTO review_files (file_id, review_id) SELECT DISTINCT rrf.file_id, ra.review_id FROM review_round_files rrf, review_assignments ra WHERE ra.review_round_id = rrf.review_round_id</query>
	</sql>
	<!-- Bug #8212: Log generalization from monograph to submission -->
	<sql>
		<query>UPDATE event_log_settings SET setting_name = 'submissionId' WHERE setting_name = 'monographId'</query>
		<query>UPDATE event_log SET message='submission.event.submissionSubmitted' WHERE message='submission.event.monographSubmitted'</query>
	</sql>
	<!-- Bug #8212: Refactor MailTemplate code into PKP lib -->
	<sql>
		<!-- pressName becomes contextName -->
		<query>UPDATE email_templates_default_data SET body=REPLACE(body, '{$pressName}', '{$contextName}'), subject=REPLACE(subject, '{$pressName}', '{$contextName}')</query>
		<query>UPDATE email_templates_data SET body=REPLACE(body, '{$pressName}', '{$contextName}'), subject=REPLACE(subject, '{$pressName}', '{$contextName}')</query>
		<!-- pressUrl becomes contextUrl -->
		<query>UPDATE email_templates_default_data SET body=REPLACE(body, '{$pressUrl}', '{$contextUrl}'), subject=REPLACE(subject, '{$pressUrl}', '{$contextUrl}')</query>
		<query>UPDATE email_templates_data SET body=REPLACE(body, '{$pressUrl}', '{$contextUrl}'), subject=REPLACE(subject, '{$pressUrl}', '{$contextUrl}')</query>
		<!-- monographTitle becomes submissionTitle -->
		<query>UPDATE email_templates_default_data SET body=REPLACE(body, '{$monographTitle}', '{$submissionTitle}'), subject=REPLACE(subject, '{$monographTitle}', '{$submissionTitle}')</query>
		<query>UPDATE email_templates_data SET body=REPLACE(body, '{$monographTitle}', '{$submissionTitle}'), subject=REPLACE(subject, '{$monographTitle}', '{$submissionTitle}')</query>
		<!-- monographId becomes submissionId -->
		<query>UPDATE email_templates_default_data SET body=REPLACE(body, '{$monographId}', '{$submissionId}'), subject=REPLACE(subject, '{$monographId}', '{$submissionId}')</query>
		<query>UPDATE email_templates_data SET body=REPLACE(body, '{$monographId}', '{$submissionId}'), subject=REPLACE(subject, '{$monographId}', '{$submissionId}')</query>
		<!-- monographAbstract becomes submissionAbstract -->
		<query>UPDATE email_templates_default_data SET body=REPLACE(body, '{$monographAbstract}', '{$submissionAbstract}'), subject=REPLACE(subject, '{$monographAbstract}', '{$submissionAbstract}')</query>
		<query>UPDATE email_templates_data SET body=REPLACE(body, '{$monographAbstract}', '{$submissionAbstract}'), subject=REPLACE(subject, '{$monographAbstract}', '{$submissionAbstract}')</query>
	</sql>
</data>

=== jardakotesovec/pkp-mono/pkp-lib/xml/data/filter_groups.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE data SYSTEM "../../../lib/pkp/dtd/xmlData.dtd">

<!--
  * controlled_vocab.xml
  *
  * Copyright (c) 2003-2010 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * Definition of filter groups.
  -->
<data>
	<table name="filter_groups">
		<!-- citation parsers (citation extraction services) -->
		<row>
			<field name="symbolic">plaintext=>nlm30-element-citation</field>
			<field name="display_name">Citation Extraction Services</field>
			<field name="description">Convert a plain text citation into NLM 3.0 element-citation mark-up.</field>
			<field name="input_type">primitive::string</field>
			<field name="output_type">metadata::lib.pkp.plugins.metadata.nlm30.schema.Nlm30CitationSchema(CITATION)</field>
		</row>

		<!-- citation lookup (citation database/improvement/lookup services) -->
		<row>
			<field name="symbolic">nlm30-element-citation=>nlm30-element-citation</field>
			<field name="display_name">Citation Database Services</field>
			<field name="description">Improve NLM 3.0 element-citation mark-up, e.g. by looking up citations in external databases.</field>
			<field name="input_type">metadata::lib.pkp.plugins.metadata.nlm30.schema.Nlm30CitationSchema(CITATION)</field>
			<field name="output_type">metadata::lib.pkp.plugins.metadata.nlm30.schema.Nlm30CitationSchema(CITATION)</field>
		</row>

		<!-- ISBN lookup and extraction services -->
		<row>
			<field name="symbolic">nlm30-element-citation=>isbn</field>
			<field name="display_name">ISBN extraction service</field>
			<field name="description">Find an ISBN for a given NLM 3.0 element-citation description.</field>
			<field name="input_type">metadata::lib.pkp.plugins.metadata.nlm30.schema.Nlm30CitationSchema(CITATION)</field>
			<field name="output_type">primitive::string</field>
		</row>
		<row>
			<field name="symbolic">isbn=>nlm30-element-citation</field>
			<field name="display_name">ISBN lookup service</field>
			<field name="description">Look up a full NLM 3.0 element-citation description with a given ISBN.</field>
			<field name="input_type">primitive::string</field>
			<field name="output_type">metadata::lib.pkp.plugins.metadata.nlm30.schema.Nlm30CitationSchema(CITATION)</field>
		</row>

		<!-- citation output -->
		<row>
			<field name="symbolic">nlm30-element-citation=>plaintext</field>
			<field name="display_name">Citation Output Services</field>
			<field name="description">Convert NLM 3.0 element-citation mark-up into a plain-text citation output standard.</field>
			<field name="input_type">metadata::lib.pkp.plugins.metadata.nlm30.schema.Nlm30CitationSchema(CITATION)</field>
			<field name="output_type">primitive::string</field>
		</row>

		<!-- NLM 3.0 output -->
		<row>
			<field name="symbolic">submission=>nlm30-article</field>
			<field name="display_name">NLM 3.0 Journal Publishing Output</field>
			<field name="description">Convert an OJS or OCS article/paper into NLM 3.0.</field>
			<field name="input_type">class::lib.pkp.classes.submission.Submission</field>
			<!-- FIXME: Add NLM 3.0 tag set schema validation as soon as we implement the full tag set, see #5648 -->
			<field name="output_type">xml::*</field>
		</row>
		
		<!-- NLM 2.3 output -->
		<row>
			<field name="symbolic">submission=>nlm23-article</field>
			<field name="display_name">NLM 2.3 Journal Publishing Output</field>
			<field name="description">Convert an OJS or OCS article/paper into NLM 2.3.</field>
			<field name="input_type">class::lib.pkp.classes.submission.Submission</field>
			<!-- FIXME: Add NLM 2.3 tag set schema validation as soon as we implement the full tag set, see #5648 -->
			<field name="output_type">xml::*</field>
		</row>
		
		<!-- NLM 3.0 to 2.3 downgrade -->
		<row>
			<field name="symbolic">nlm30-article=>nlm23-article</field>
			<field name="display_name">NLM 3.0 to 2.3 Journal Publishing Downgrade</field>
			<field name="description">Downgrades NLM 3.0 to NLM 2.3.</field>
			<!-- FIXME: Add NLM 2.3 and 3.0 tag set schema validation as soon as we implement the full tag set, see #5648 -->
			<field name="input_type">xml::*</field>
			<field name="output_type">xml::*</field>
		</row>
		
		<!-- Plain text reference list output -->
		<row>
			<field name="symbolic">submission=>reference-list</field>
			<field name="display_name">Plain text reference list generation</field>
			<field name="description">Generate a formatted plain text reference list from an OJS/OCS/OMP submission's references</field>
			<field name="input_type">class::lib.pkp.classes.submission.Submission</field>
			<field name="output_type">class::lib.pkp.classes.citation.PlainTextReferencesList</field>
		</row>
	</table>
</data>
